[project]
name = "PiicoDev-SSD1306"
version = "1.10.2"
description = "Drivers for the PiicoDev ecosystem of sensors and modules"
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name="Core Electronics", email="production.inbox@coreelectronics.com.au" }
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: MicroPython",
]

dependencies = [
    "PiicoDev_Unified @ git+https://github.com/garynthompson/CE-PiicoDev-Unified.git@garys"
]

[project.urls]
Homepage = "https://core-electronics.com.au/piicodev-oled-display-module-128x64-ssd1306.html"
Documentation = "https://core-electronics.com.au/guides/raspberry-pi-pico/piicodev-oled-ssd1306-raspberry-pi-pico-guide/"
Repository = "https://github.com/CoreElectronics/CE-PiicoDev-SSD1306-MicroPython-Module"
Issues = "https://github.com/CoreElectronics/CE-PiicoDev-SSD1306-MicroPython-Module/issues"
#Changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"

[tool.setuptools]
py-modules = ["PiicoDev_SSD1306"]

# install the font into site‑packages/share/piicodev‑ssd1306
[tool.setuptools.data-files]
"share/piicodev-ssd1306" = ["font-pet-me-128.dat"]

[project.optional-dependencies]
dev = [
    "python-minifier @ git+https://github.com/garynthompson/python-minifier.git@remove_unused_platforms"
]

